name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      #      - name: Run Linter
      #        run: npm run lint

      - name: Run Tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: .svelte-kit

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: 'MyPlesk'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/vhosts/silver-events.fr/SilverEvents/
            pwd
            
            git pull origin main
            
            /var/www/vhosts/silver-events.fr/.nodenv/shims/npm ci
            /var/www/vhosts/silver-events.fr/.nodenv/shims/npm run build
            /var/www/vhosts/silver-events.fr/.nodenv/shims/npx prisma migrate deploy --schema=./prisma/schema.production.prisma
            /var/www/vhosts/silver-events.fr/.nodenv/shims/node --env-file=.env build
